# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Athos/Documents/GitHub/ProvaProgetto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Athos/Documents/GitHub/ProvaProgetto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Athos/Documents/GitHub/ProvaProgetto/CMakeFiles /Users/Athos/Documents/GitHub/ProvaProgetto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Athos/Documents/GitHub/ProvaProgetto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named core

# Build rule for target.
core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 core
.PHONY : core

# fast build rule for target.
core/fast:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/build
.PHONY : core/fast

#=============================================================================
# Target rules for targets named FlyJoyride

# Build rule for target.
FlyJoyride: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FlyJoyride
.PHONY : FlyJoyride

# fast build rule for target.
FlyJoyride/fast:
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/build
.PHONY : FlyJoyride/fast

#=============================================================================
# Target rules for targets named runAllTests

# Build rule for target.
runAllTests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 runAllTests
.PHONY : runAllTests

# fast build rule for target.
runAllTests/fast:
	$(MAKE) -f Test/CMakeFiles/runAllTests.dir/build.make Test/CMakeFiles/runAllTests.dir/build
.PHONY : runAllTests/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f Test/lib/googletest/CMakeFiles/gtest_main.dir/build.make Test/lib/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f Test/lib/googletest/CMakeFiles/gtest.dir/build.make Test/lib/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

Achievement.o: Achievement.cpp.o

.PHONY : Achievement.o

# target to build an object file
Achievement.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Achievement.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Achievement.cpp.o
.PHONY : Achievement.cpp.o

Achievement.i: Achievement.cpp.i

.PHONY : Achievement.i

# target to preprocess a source file
Achievement.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Achievement.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Achievement.cpp.i
.PHONY : Achievement.cpp.i

Achievement.s: Achievement.cpp.s

.PHONY : Achievement.s

# target to generate assembly for a file
Achievement.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Achievement.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Achievement.cpp.s
.PHONY : Achievement.cpp.s

BlockFactory.o: BlockFactory.cpp.o

.PHONY : BlockFactory.o

# target to build an object file
BlockFactory.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/BlockFactory.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/BlockFactory.cpp.o
.PHONY : BlockFactory.cpp.o

BlockFactory.i: BlockFactory.cpp.i

.PHONY : BlockFactory.i

# target to preprocess a source file
BlockFactory.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/BlockFactory.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/BlockFactory.cpp.i
.PHONY : BlockFactory.cpp.i

BlockFactory.s: BlockFactory.cpp.s

.PHONY : BlockFactory.s

# target to generate assembly for a file
BlockFactory.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/BlockFactory.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/BlockFactory.cpp.s
.PHONY : BlockFactory.cpp.s

Character.o: Character.cpp.o

.PHONY : Character.o

# target to build an object file
Character.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Character.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Character.cpp.o
.PHONY : Character.cpp.o

Character.i: Character.cpp.i

.PHONY : Character.i

# target to preprocess a source file
Character.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Character.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Character.cpp.i
.PHONY : Character.cpp.i

Character.s: Character.cpp.s

.PHONY : Character.s

# target to generate assembly for a file
Character.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Character.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Character.cpp.s
.PHONY : Character.cpp.s

EnemyFactory.o: EnemyFactory.cpp.o

.PHONY : EnemyFactory.o

# target to build an object file
EnemyFactory.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/EnemyFactory.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/EnemyFactory.cpp.o
.PHONY : EnemyFactory.cpp.o

EnemyFactory.i: EnemyFactory.cpp.i

.PHONY : EnemyFactory.i

# target to preprocess a source file
EnemyFactory.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/EnemyFactory.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/EnemyFactory.cpp.i
.PHONY : EnemyFactory.cpp.i

EnemyFactory.s: EnemyFactory.cpp.s

.PHONY : EnemyFactory.s

# target to generate assembly for a file
EnemyFactory.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/EnemyFactory.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/EnemyFactory.cpp.s
.PHONY : EnemyFactory.cpp.s

FlyingEnemy.o: FlyingEnemy.cpp.o

.PHONY : FlyingEnemy.o

# target to build an object file
FlyingEnemy.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/FlyingEnemy.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/FlyingEnemy.cpp.o
.PHONY : FlyingEnemy.cpp.o

FlyingEnemy.i: FlyingEnemy.cpp.i

.PHONY : FlyingEnemy.i

# target to preprocess a source file
FlyingEnemy.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/FlyingEnemy.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/FlyingEnemy.cpp.i
.PHONY : FlyingEnemy.cpp.i

FlyingEnemy.s: FlyingEnemy.cpp.s

.PHONY : FlyingEnemy.s

# target to generate assembly for a file
FlyingEnemy.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/FlyingEnemy.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/FlyingEnemy.cpp.s
.PHONY : FlyingEnemy.cpp.s

Game.o: Game.cpp.o

.PHONY : Game.o

# target to build an object file
Game.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Game.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Game.cpp.o
.PHONY : Game.cpp.o

Game.i: Game.cpp.i

.PHONY : Game.i

# target to preprocess a source file
Game.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Game.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Game.cpp.i
.PHONY : Game.cpp.i

Game.s: Game.cpp.s

.PHONY : Game.s

# target to generate assembly for a file
Game.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Game.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Game.cpp.s
.PHONY : Game.cpp.s

NormalBlock.o: NormalBlock.cpp.o

.PHONY : NormalBlock.o

# target to build an object file
NormalBlock.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/NormalBlock.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/NormalBlock.cpp.o
.PHONY : NormalBlock.cpp.o

NormalBlock.i: NormalBlock.cpp.i

.PHONY : NormalBlock.i

# target to preprocess a source file
NormalBlock.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/NormalBlock.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/NormalBlock.cpp.i
.PHONY : NormalBlock.cpp.i

NormalBlock.s: NormalBlock.cpp.s

.PHONY : NormalBlock.s

# target to generate assembly for a file
NormalBlock.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/NormalBlock.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/NormalBlock.cpp.s
.PHONY : NormalBlock.cpp.s

PowerUpBlock.o: PowerUpBlock.cpp.o

.PHONY : PowerUpBlock.o

# target to build an object file
PowerUpBlock.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/PowerUpBlock.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/PowerUpBlock.cpp.o
.PHONY : PowerUpBlock.cpp.o

PowerUpBlock.i: PowerUpBlock.cpp.i

.PHONY : PowerUpBlock.i

# target to preprocess a source file
PowerUpBlock.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/PowerUpBlock.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/PowerUpBlock.cpp.i
.PHONY : PowerUpBlock.cpp.i

PowerUpBlock.s: PowerUpBlock.cpp.s

.PHONY : PowerUpBlock.s

# target to generate assembly for a file
PowerUpBlock.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/PowerUpBlock.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/PowerUpBlock.cpp.s
.PHONY : PowerUpBlock.cpp.s

ShootingEnemy.o: ShootingEnemy.cpp.o

.PHONY : ShootingEnemy.o

# target to build an object file
ShootingEnemy.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/ShootingEnemy.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/ShootingEnemy.cpp.o
.PHONY : ShootingEnemy.cpp.o

ShootingEnemy.i: ShootingEnemy.cpp.i

.PHONY : ShootingEnemy.i

# target to preprocess a source file
ShootingEnemy.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/ShootingEnemy.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/ShootingEnemy.cpp.i
.PHONY : ShootingEnemy.cpp.i

ShootingEnemy.s: ShootingEnemy.cpp.s

.PHONY : ShootingEnemy.s

# target to generate assembly for a file
ShootingEnemy.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/ShootingEnemy.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/ShootingEnemy.cpp.s
.PHONY : ShootingEnemy.cpp.s

Window.o: Window.cpp.o

.PHONY : Window.o

# target to build an object file
Window.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Window.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Window.cpp.o
.PHONY : Window.cpp.o

Window.i: Window.cpp.i

.PHONY : Window.i

# target to preprocess a source file
Window.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Window.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Window.cpp.i
.PHONY : Window.cpp.i

Window.s: Window.cpp.s

.PHONY : Window.s

# target to generate assembly for a file
Window.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/Window.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/Window.cpp.s
.PHONY : Window.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.o
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.i
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/core.dir/build.make CMakeFiles/core.dir/main.cpp.s
	$(MAKE) -f CMakeFiles/FlyJoyride.dir/build.make CMakeFiles/FlyJoyride.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... core"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FlyJoyride"
	@echo "... runAllTests"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... Achievement.o"
	@echo "... Achievement.i"
	@echo "... Achievement.s"
	@echo "... BlockFactory.o"
	@echo "... BlockFactory.i"
	@echo "... BlockFactory.s"
	@echo "... Character.o"
	@echo "... Character.i"
	@echo "... Character.s"
	@echo "... EnemyFactory.o"
	@echo "... EnemyFactory.i"
	@echo "... EnemyFactory.s"
	@echo "... FlyingEnemy.o"
	@echo "... FlyingEnemy.i"
	@echo "... FlyingEnemy.s"
	@echo "... Game.o"
	@echo "... Game.i"
	@echo "... Game.s"
	@echo "... NormalBlock.o"
	@echo "... NormalBlock.i"
	@echo "... NormalBlock.s"
	@echo "... PowerUpBlock.o"
	@echo "... PowerUpBlock.i"
	@echo "... PowerUpBlock.s"
	@echo "... ShootingEnemy.o"
	@echo "... ShootingEnemy.i"
	@echo "... ShootingEnemy.s"
	@echo "... Window.o"
	@echo "... Window.i"
	@echo "... Window.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

